version: "3"

services:
  app:
    container_name: setup-node
    build:
      context: .
      dockerfile: Dockerfile
      target: BUILDER
    volumes:
      - ./:/usr/app
    environment:
      - PORT=3000
    ports:
      - 3000:3000
